PROVINCES = [
    "Kigali City",
    "Eastern Province",
    "Northern Province",
    "Southern Province",
    "Western Province",
]

DISTRICTS = {
    "Kigali City": ["Gasabo", "Kicukiro", "Nyarugenge"],
    "Eastern Province": [
        "Bugesera",
        "Gatsibo",
        "Kayonza",
        "Kirehe",
        "Ngoma",
        "Nyagatare",
        "Rwamagana",
    ],
    "Northern Province": [
        "Burera",
        "Gakenke",
        "Gicumbi",
        "Musanze",
        "Rulindo",
    ],
    "Southern Province": [
        "Gisagara",
        "Huye",
        "Kamonyi",
        "Muhanga",
        "Nyamagabe",
        "Nyanza",
        "Nyaruguru",
        "Ruhango",
    ],
    "Western Province": [
        "Karongi",
        "Ngororero",
        "Nyabihu",
        "Nyamasheke",
        "Rubavu",
        "Rusizi",
        "Rutsiro",
    ],
}

DISTRICT_ALIASES = {
    "kigali": "Kigali City",
    "gasabo": "Gasabo",
    "kicukiro": "Kicukiro",
    "nyarugenge": "Nyarugenge",
    "bugesera": "Bugesera",
    "gatsibo": "Gatsibo",
    "kayonza": "Kayonza",
    "kirehe": "Kirehe",
    "ngoma": "Ngoma",
    "nyagatare": "Nyagatare",
    "rwamagana": "Rwamagana",
    "burera": "Burera",
    "gakenke": "Gakenke",
    "gicumbi": "Gicumbi",
    "musanze": "Musanze",
    "rulindo": "Rulindo",
    "gisagara": "Gisagara",
    "huye": "Huye",
    "kamonyi": "Kamonyi",
    "muhanga": "Muhanga",
    "nyamagabe": "Nyamagabe",
    "nyanza": "Nyanza",
    "nyaruguru": "Nyaruguru",
    "ruhango": "Ruhango",
    "karongi": "Karongi",
    "ngororero": "Ngororero",
    "nyabihu": "Nyabihu",
    "nyamasheke": "Nyamasheke",
    "rubavu": "Rubavu",
    "rusizi": "Rusizi",
    "rutsiro": "Rutsiro",
}
