import { ApiUser, Location, NotificationItem, Outage, Report, Subscription, Utility } from './client';

export const mockUser: ApiUser = {
    id: 'user-admin-1',
    phone: '0780000000',
    firstName: 'Admin',
    lastName: 'User',
    email: 'admin@rwanda-utility.rw',
    role: 'ADMIN',
    notificationsEnabled: true,
};

export const mockUtilities: Utility[] = [
    {
        id: 'util-reg-1',
        name: 'Electricity',
        code: 'REG',
        description: 'Rwanda Energy Group (REG / EUCL)',
        isActive: true,
        createdAt: '2026-01-01T00:00:00Z',
        updatedAt: '2026-01-01T00:00:00Z',
    },
    {
        id: 'util-wasac-2',
        name: 'Water',
        code: 'WASAC',
        description: 'Water and Sanitation Corporation (WASAC)',
        isActive: true,
        createdAt: '2026-01-01T00:00:00Z',
        updatedAt: '2026-01-01T00:00:00Z',
    },
];

export const mockLocations: Location[] = [
    { id: 'loc-kigali-all', province: 'Kigali City', district: 'Kigali City', sector: 'All Sectors', cell: null, village: null, createdAt: '', updatedAt: '' },
    { id: 'loc-gasabo-1', province: 'Kigali City', district: 'Gasabo District', sector: 'Kimironko', cell: 'Kibagabaga', village: null, createdAt: '', updatedAt: '' },
    { id: 'loc-nyarugenge-1', province: 'Kigali City', district: 'Nyarugenge District', sector: 'Nyamirambo', cell: 'Rwezamenyo', village: null, createdAt: '', updatedAt: '' },
    { id: 'loc-kicukiro-1', province: 'Kigali City', district: 'Kicukiro District', sector: 'Niboye', cell: 'Gatenga', village: null, createdAt: '', updatedAt: '' },
    { id: 'loc-rwamagana-1', province: 'Eastern Province', district: 'Rwamagana District', sector: 'Kigabiro', cell: null, village: null, createdAt: '', updatedAt: '' },
    { id: 'loc-muhanga-1', province: 'Southern Province', district: 'Muhanga District', sector: 'Nyamabuye', cell: null, village: null, createdAt: '', updatedAt: '' },
    { id: 'loc-musanze-1', province: 'Northern Province', district: 'Musanze District', sector: 'Muhoza', cell: null, village: null, createdAt: '', updatedAt: '' },
    { id: 'loc-rubavu-1', province: 'Western Province', district: 'Rubavu District', sector: 'Gisenyi', cell: null, village: null, createdAt: '', updatedAt: '' },
];

export const mockOutages: Outage[] = [
    {
        id: 'outage-kigali-1',
        title: 'Kigali City',
        description: 'Scheduled maintenance and grid upgrading affecting central network distribution lines.',
        status: 'Scheduled Outage',
        startTime: 'Sep 9, 2026 · 10:00 AM',
        endTime: '2:00 PM',
        utility: { name: 'Electricity', code: 'REG' },
        sourceName: 'REG (Rwanda Energy Group)',
        sourceType: 'OFFICIAL',
        outageLocations: [
            { location: { district: 'Kigali City (all sectors)', sector: 'Nyamirambo' } },
            { location: { district: 'Kacyiru', sector: null } },
            { location: { district: 'Gacuriro', sector: null } },
        ],
    },
    {
        id: 'outage-gasabo-2',
        title: 'Gasabo District',
        description: 'Substation maintenance and line replacement in Kimironko and Kibagabaga feeders.',
        status: 'Scheduled Outage',
        startTime: 'Sep 10, 2026 · 9:00 AM',
        endTime: '1:00 PM',
        utility: { name: 'Electricity', code: 'REG' },
        sourceName: 'REG (Rwanda Energy Group)',
        sourceType: 'OFFICIAL',
        outageLocations: [{ location: { district: 'Gasabo District', sector: 'Kimironko' } }],
    },
    {
        id: 'outage-nyarugenge-3',
        title: 'Nyarugenge District',
        description: 'Transformer upgrade and maintenance across Nyamirambo sector.',
        status: 'Scheduled Outage',
        startTime: 'Sep 11, 2026 · 8:00 AM',
        endTime: '12:00 PM',
        utility: { name: 'Electricity', code: 'REG' },
        sourceName: 'REG (Rwanda Energy Group)',
        sourceType: 'OFFICIAL',
        outageLocations: [{ location: { district: 'Nyarugenge District', sector: 'Nyamirambo' } }],
    },
    {
        id: 'outage-rwamagana-4',
        title: 'Rwamagana District',
        description: 'High-voltage line clearing and preventive substation servicing.',
        status: 'Scheduled Outage',
        startTime: 'Sep 12, 2026 · 9:00 AM',
        endTime: '3:00 PM',
        utility: { name: 'Electricity', code: 'REG' },
        sourceName: 'REG (Rwanda Energy Group)',
        sourceType: 'OFFICIAL',
        outageLocations: [{ location: { district: 'Rwamagana District', sector: 'Kigabiro' } }],
    },
    {
        id: 'outage-muhanga-5',
        title: 'Muhanga District',
        description: 'Relocation of utility poles for bypass road construction project.',
        status: 'Scheduled Outage',
        startTime: 'Sep 13, 2026 · 10:00 AM',
        endTime: '2:00 PM',
        utility: { name: 'Electricity', code: 'REG' },
        sourceName: 'REG (Rwanda Energy Group)',
        sourceType: 'OFFICIAL',
        outageLocations: [{ location: { district: 'Muhanga District', sector: 'Nyamabuye' } }],
    },
    {
        id: 'outage-musanze-6',
        title: 'Musanze District',
        description: 'Network maintenance and feeder inspection in Muhoza town center.',
        status: 'Scheduled Outage',
        startTime: 'Sep 14, 2026 · 8:30 AM',
        endTime: '1:30 PM',
        utility: { name: 'Electricity', code: 'REG' },
        sourceName: 'REG (Rwanda Energy Group)',
        sourceType: 'OFFICIAL',
        outageLocations: [{ location: { district: 'Musanze District', sector: 'Muhoza' } }],
    },
    {
        id: 'outage-rubavu-7',
        title: 'Rubavu District',
        description: 'Main pump station overhaul and pressure pipe repairs.',
        status: 'Scheduled Outage',
        startTime: 'Sep 15, 2026 · 9:00 AM',
        endTime: '2:00 PM',
        utility: { name: 'Water', code: 'WASAC' },
        sourceName: 'WASAC',
        sourceType: 'OFFICIAL',
        outageLocations: [{ location: { district: 'Rubavu District', sector: 'Gisenyi' } }],
    },
    {
        id: 'outage-huye-8',
        title: 'Huye District',
        description: 'Power distribution line upgrade along university corridor.',
        status: 'Scheduled Outage',
        startTime: 'Sep 16, 2026 · 10:00 AM',
        endTime: '4:00 PM',
        utility: { name: 'Electricity', code: 'REG' },
        sourceName: 'REG (Rwanda Energy Group)',
        sourceType: 'OFFICIAL',
        outageLocations: [{ location: { district: 'Huye District', sector: 'Ngoma' } }],
    },
    {
        id: 'outage-rusizi-9',
        title: 'Rusizi District',
        description: 'Water treatment plant maintenance and valve replacements.',
        status: 'Scheduled Outage',
        startTime: 'Sep 17, 2026 · 7:00 AM',
        endTime: '1:00 PM',
        utility: { name: 'Water', code: 'WASAC' },
        sourceName: 'WASAC',
        sourceType: 'OFFICIAL',
        outageLocations: [{ location: { district: 'Rusizi District', sector: 'Kamembe' } }],
    },
    {
        id: 'outage-bugesera-10',
        title: 'Bugesera District',
        description: 'Electrification connection work for the new industrial park zone.',
        status: 'Scheduled Outage',
        startTime: 'Sep 18, 2026 · 8:00 AM',
        endTime: '12:00 PM',
        utility: { name: 'Electricity', code: 'REG' },
        sourceName: 'REG (Rwanda Energy Group)',
        sourceType: 'OFFICIAL',
        outageLocations: [{ location: { district: 'Bugesera District', sector: 'Nyamata' } }],
    },
    {
        id: 'outage-kayonza-11',
        title: 'Kayonza District',
        description: 'Scheduled grid inspection and pole replacement in Mukarange.',
        status: 'Scheduled Outage',
        startTime: 'Sep 19, 2026 · 9:30 AM',
        endTime: '3:30 PM',
        utility: { name: 'Electricity', code: 'REG' },
        sourceName: 'REG (Rwanda Energy Group)',
        sourceType: 'OFFICIAL',
        outageLocations: [{ location: { district: 'Kayonza District', sector: 'Mukarange' } }],
    },
];

export const mockSubscriptions: Subscription[] = [
    {
        id: 'sub-1',
        userId: 'user-admin-1',
        locationId: 'loc-gasabo-1',
        utilityId: 'util-reg-1',
        isActive: true,
        createdAt: '2026-08-01T10:00:00Z',
        updatedAt: '2026-08-01T10:00:00Z',
        location: {
            id: 'loc-gasabo-1',
            province: 'Kigali City',
            district: 'Gasabo District',
            sector: 'Kimironko',
            cell: null,
            village: null,
            createdAt: '',
            updatedAt: '',
        },
        utility: {
            id: 'util-reg-1',
            name: 'Electricity',
            code: 'REG',
            description: 'Rwanda Energy Group',
            isActive: true,
            createdAt: '',
            updatedAt: '',
        },
    },
    {
        id: 'sub-2',
        userId: 'user-admin-1',
        locationId: 'loc-nyarugenge-1',
        utilityId: 'util-wasac-2',
        isActive: true,
        createdAt: '2026-08-05T12:00:00Z',
        updatedAt: '2026-08-05T12:00:00Z',
        location: {
            id: 'loc-nyarugenge-1',
            province: 'Kigali City',
            district: 'Nyarugenge District',
            sector: 'Nyamirambo',
            cell: null,
            village: null,
            createdAt: '',
            updatedAt: '',
        },
        utility: {
            id: 'util-wasac-2',
            name: 'Water',
            code: 'WASAC',
            description: 'WASAC Water Utility',
            isActive: true,
            createdAt: '',
            updatedAt: '',
        },
    },
    {
        id: 'sub-3',
        userId: 'user-admin-1',
        locationId: 'loc-kicukiro-1',
        utilityId: 'util-reg-1',
        isActive: true,
        createdAt: '2026-08-10T08:00:00Z',
        updatedAt: '2026-08-10T08:00:00Z',
        location: {
            id: 'loc-kicukiro-1',
            province: 'Kigali City',
            district: 'Kicukiro District',
            sector: 'Niboye',
            cell: null,
            village: null,
            createdAt: '',
            updatedAt: '',
        },
        utility: {
            id: 'util-reg-1',
            name: 'Electricity',
            code: 'REG',
            description: 'Rwanda Energy Group',
            isActive: true,
            createdAt: '',
            updatedAt: '',
        },
    },
];

export const mockNotifications: NotificationItem[] = [
    {
        id: 'notif-1',
        userId: 'user-admin-1',
        outageId: 'outage-kigali-1',
        title: 'New Outage Alert',
        message: 'Kigali City - Electricity',
        isRead: false,
        status: 'UNREAD',
        createdAt: 'Sep 9, 2026 · 9:30 AM',
        sentAt: 'Sep 9, 2026 · 9:30 AM',
    },
    {
        id: 'notif-2',
        userId: 'user-admin-1',
        outageId: 'outage-gasabo-2',
        title: 'Outage Update',
        message: 'Gasabo District - Electricity',
        isRead: true,
        status: 'READ',
        createdAt: 'Sep 9, 2026 · 8:15 AM',
        sentAt: 'Sep 9, 2026 · 8:15 AM',
    },
    {
        id: 'notif-3',
        userId: 'user-admin-1',
        outageId: 'outage-nyarugenge-3',
        title: 'Service Restored',
        message: 'Nyarugenge District - Water',
        isRead: true,
        status: 'READ',
        createdAt: 'Sep 8, 2026 · 6:45 PM',
        sentAt: 'Sep 8, 2026 · 6:45 PM',
    },
    {
        id: 'notif-4',
        userId: 'user-admin-1',
        outageId: 'outage-report-1234',
        title: 'New Report Status',
        message: 'Report #1234 - In Progress',
        isRead: true,
        status: 'READ',
        createdAt: 'Sep 8, 2026 · 2:20 PM',
        sentAt: 'Sep 8, 2026 · 2:20 PM',
    },
    {
        id: 'notif-5',
        userId: 'user-admin-1',
        outageId: 'outage-rwamagana-4',
        title: 'New Outage Alert',
        message: 'Rwamagana District - Electricity',
        isRead: true,
        status: 'READ',
        createdAt: 'Sep 8, 2026 · 11:10 AM',
        sentAt: 'Sep 8, 2026 · 11:10 AM',
    },
];

export const mockReports: Report[] = [];

export const mockDeviceId = 'a3f2e1c9-8b7d-4e6f-b2a1-0d9e7f6c1234';
