import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConfigModule } from '@nestjs/config';
import { ThrottlerGuard, ThrottlerModule } from '@nestjs/throttler';
import { APP_GUARD } from '@nestjs/core';
import { BullModule } from '@nestjs/bullmq';
import { ConfigService } from '@nestjs/config';
import { AppController } from './app.controller';
import { UsersModule } from './users/users.module';
import { LocationsModule } from './locations/locations.module';
import { UtilitiesModule } from './utilities/utilities.module';
import { SubscriptionsModule } from './subscriptions/subscriptions.module';
import { OutagesModule } from './outages/outages.module';
import { DevicesModule } from './devices/devices.module';
import { NotificationsModule } from './notifications/notifications.module';
import { ReportsModule } from './reports/reports.module';
import { AuthModule } from './auth/auth.module';
import { DataSourcesModule } from './data-sources/data-sources.module';
import { AdminModule } from './admin/admin.module';

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      envFilePath: '.env',
    }),

    ThrottlerModule.forRoot([
      {
        name: 'default',
        // ttl is in milliseconds. Generous because many phones in Rwanda share
        // an IP address behind mobile-carrier NAT.
        ttl: 60_000,
        limit: 300,
      },
    ]),

    BullModule.forRootAsync({
      inject: [ConfigService],
      useFactory: (config: ConfigService) => ({
        connection: {
          host: config.get<string>('REDIS_HOST', 'localhost'),
          port: Number(config.get<string>('REDIS_PORT', '6379')),
          password: config.get<string>('REDIS_PASSWORD') || undefined,
          db: Number(config.get<string>('REDIS_DB', '0')),
        },
      }),
    }),

    TypeOrmModule.forRoot({
      type: 'postgres',
      host: process.env.DATABASE_HOST || 'localhost',
      port: Number(process.env.DATABASE_PORT || 5433),
      username: process.env.DATABASE_USER || 'utility_admin',
      password: process.env.DATABASE_PASSWORD || 'utility_password',
      database: process.env.DATABASE_NAME || 'utility_alerts',
      autoLoadEntities: true,
      // Schema auto-sync is convenient in development; set DB_SYNCHRONIZE=false
      // in production once migrations are in place.
      synchronize: process.env.DB_SYNCHRONIZE !== 'false',
      // Timestamps are stored without a time zone. Run every database session
      // in Kigali time so values generated by PostgreSQL (createdAt, now())
      // match the Kigali wall-clock times written by the API.
      extra: { options: '-c timezone=Africa/Kigali' },
    }),

    UsersModule,
    LocationsModule,
    UtilitiesModule,
    SubscriptionsModule,
    OutagesModule,
    DevicesModule,
    NotificationsModule,
    ReportsModule,
    AuthModule,
    DataSourcesModule,
    AdminModule,
  ],

  controllers: [AppController],
  providers: [{ provide: APP_GUARD, useClass: ThrottlerGuard }],
})
export class AppModule { }